//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROEKTEntities4 : DbContext
    {
        private static PROEKTEntities4 _context;
        public PROEKTEntities4()
            : base("name=PROEKTEntities4")
        {
        }
        public static PROEKTEntities4 GetContext()
        {
            if( _context == null )
                _context = new PROEKTEntities4();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduleClient> ScheduleClient { get; set; }
        public virtual DbSet<Treners> Treners { get; set; }
    }
}
