//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treners
    {
        public int Id_Trener { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public byte[] Photo { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> IdDirection { get; set; }
    
        public virtual Direction Direction { get; set; }
    }
}
